print("Hospital Appointment Booking System")
print("Hospital Appointment Booking System")
print("Patient Registration Module")
print("Hospital Appointment Booking System")
print("Patient Registration Module")
print("Login Feature")
print("hello")