print("Hospital Appointment Booking System")
print("Hospital Appointment Booking System")
print("Patient Registration Module")
print("Hospital Appointment Booking System")
print("Patient Registration Module")
print("Login Feature")
print("hello")
print("Hospital Appointment Booking System")
print("Main Branch: Appointment Management")
print("Main Branch: Doctor Dashboard")
